insert into status (name) values
	('Available'),
	('Adopted');
	
insert into pet (name, species, description, age, status_id) values
 ('Martelle', 'dog', 'Advanced value-added artificial intelligence', 5, 1),
 ('Kary', 'turtle', 'Decentralized asymmetric throughput', 7, 1),
 ('Bessy', 'bird', 'Fundamental incremental project', 1, 1),
 ('Bearnard', 'fish', 'Enhanced regional alliance', 8, 1),
 ('Doralynne', 'turtle', 'Customizable explicit throughput', 8, 1),
 ('Maggee', 'turtle', 'Stand-alone explicit time-frame', 4, 1),
 ('Yetty', 'bird', 'Exclusive value-added protocol', 14, 1),
 ('Ardine', 'bird', 'Multi-channelled optimizing frame', 17, 1),
 ('Matthus', 'turtle', 'Function-based real-time help-desk', 19, 1),
 ('Slade', 'dog', 'Diverse directional pricing structure', 12, 1),
 ('Tess', 'bird', 'Diverse multi-tasking policy', 17, 1),
 ('Ethelred', 'turtle', 'User-centric client-driven orchestration', 20, 1),
 ('Mike', 'bird', 'Extended zero defect solution', 11, 1),
 ('Sheelagh', 'bird', 'Advanced zero defect encryption', 7, 1),
 ('Nikolai', 'dog', 'Seamless zero tolerance projection', 13, 1),
 ('Cassey', 'cat', 'Extended bottom-line knowledge user', 8, 1),
 ('Odella', 'bird', 'Visionary empowering alliance', 20, 1),
 ('Perry', 'dog', 'Universal needs-based attitude', 18, 1),
 ('Cassie', 'turtle', 'Streamlined global moratorium', 15, 1),
 ('Martguerita', 'lizard', 'Optional upward-trending intranet', 1, 1),
 ('Jeffy', 'bird', 'Balanced 3rd generation solution', 18, 1),
 ('Linnie', 'turtle', 'Inverse clear-thinking algorithm', 15, 1),
 ('Amberly', 'dog', 'Public-key modular superstructure', 3, 1),
 ('Gaspar', 'turtle', 'Synergistic encompassing budgetary management', 14, 1),
 ('Irwinn', 'lizard', 'Centralized coherent paradigm', 16, 1),
 ('Marin', 'bird', 'Future-proofed mission-critical flexibility', 20, 1),
 ('Boyd', 'bird', 'Secured secondary implementation', 12, 1),
 ('Jedediah', 'cat', 'Robust mission-critical benchmark', 13, 1),
 ('Chip', 'cat', 'Function-based logistical firmware', 6, 1),
 ('Bald', 'cat', 'Ameliorated stable open architecture', 18, 1),
 ('Nelle', 'cat', 'Phased full-range architecture', 3, 1),
 ('Sonnie', 'dog', 'Exclusive logistical task-force', 2, 1),
 ('Ebeneser', 'fish', 'Inverse disintermediate approach', 10, 1),
 ('Viole', 'cat', 'Virtual zero tolerance ability', 9, 1),
 ('Tina', 'fish', 'Public-key maximized help-desk', 8, 1),
 ('Oralie', 'bird', 'Function-based reciprocal approach', 15, 1),
 ('Renault', 'lizard', 'Programmable optimizing frame', 7, 1),
 ('Mimi', 'turtle', 'Advanced systemic installation', 9, 1),
 ('Griff', 'fish', 'Optimized solution-oriented time-frame', 13, 1),
 ('Hinda', 'bird', 'Stand-alone secondary hardware', 12, 1),
 ('Kipp', 'cat', 'Realigned didactic approach', 15, 1),
 ('Zaria', 'bird', 'Streamlined national Graphical User Interface', 5, 1),
 ('Palm', 'lizard', 'Diverse interactive instruction set', 8, 1),
 ('Xavier', 'dog', 'Enterprise-wide content-based system engine', 16, 1),
 ('Leroi', 'dog', 'Reactive impactful encryption', 4, 1),
 ('Raoul', 'bird', 'Multi-tiered systemic projection', 4, 1),
 ('Onofredo', 'dog', 'Programmable actuating solution', 14, 1),
 ('Wade', 'fish', 'Decentralized executive workforce', 4, 1),
 ('Hurleigh', 'lizard', 'Digitized didactic definition', 14, 1),
 ('Janna', 'fish', 'Face to face 4th generation solution', 12, 1);
 
insert into user_role (name) values
	('User'),
	('Employee');

insert into person (full_name,username,passwd,role_id) values
 ('Sierra Nicholes','snicholes','pass',2),
 ('Aaron Schomer','aschomer','pass',1),
 ('Andre Levan','alevan','pass',1),
 ('Andrew Cook','acook','pass',1),
 ('Andrew Wisdom','awisdom','pass',1),
 ('Brenda Lippincott','blippincott','pass',1),
 ('Brett Dixon','bdixon','pass',1),
 ('Carlo Del Mundo','cdelmundo','pass',1),
 ('Chris Wilder','cwilder','pass',1),
 ('Christian Seefeldt','cseefeldt','pass',1),
 ('Dana Jenkins','djenkins','pass',1),
 ('Daniel Joseph','djoseph','pass',1),
 ('Ezekiel Amazigo','eamazigo','pass',1),
 ('Francisco Ponce','fponce','pass',1),
 ('Gamaliel Burgos','gburgos','pass',1),
 ('Henry De Jesus','hdejesus','pass',1),
 ('Kim Kohel-Hayes','kkohelhayes','pass',1),
 ('Matthew Kelley','mkelley','pass',1),
 ('Raquel Moura','rmoura','pass',1),
 ('Richard Duenas','rduenas','pass',1),
 ('Robert Torres','rtorres','pass',1),
 ('Romeo Erazo','rerazo','pass',1);

update pet set status_id=2 where id>5 and id<15;

commit;